// Generated by gencpp from file navio2ros/Input.msg
// DO NOT EDIT!


#ifndef NAVIO2ROS_MESSAGE_INPUT_H
#define NAVIO2ROS_MESSAGE_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navio2ros/Barometer.h>
#include <navio2ros/ADC.h>
#include <navio2ros/RC.h>
#include <navio2ros/IMU.h>
#include <navio2ros/GPS.h>

namespace navio2ros
{
template <class ContainerAllocator>
struct Input_
{
  typedef Input_<ContainerAllocator> Type;

  Input_()
    : barometer()
    , adc()
    , rc()
    , imu()
    , gps()  {
    }
  Input_(const ContainerAllocator& _alloc)
    : barometer(_alloc)
    , adc(_alloc)
    , rc(_alloc)
    , imu(_alloc)
    , gps(_alloc)  {
  (void)_alloc;
    }



   typedef  ::navio2ros::Barometer_<ContainerAllocator>  _barometer_type;
  _barometer_type barometer;

   typedef  ::navio2ros::ADC_<ContainerAllocator>  _adc_type;
  _adc_type adc;

   typedef  ::navio2ros::RC_<ContainerAllocator>  _rc_type;
  _rc_type rc;

   typedef  ::navio2ros::IMU_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef  ::navio2ros::GPS_<ContainerAllocator>  _gps_type;
  _gps_type gps;




  typedef boost::shared_ptr< ::navio2ros::Input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navio2ros::Input_<ContainerAllocator> const> ConstPtr;

}; // struct Input_

typedef ::navio2ros::Input_<std::allocator<void> > Input;

typedef boost::shared_ptr< ::navio2ros::Input > InputPtr;
typedef boost::shared_ptr< ::navio2ros::Input const> InputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navio2ros::Input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navio2ros::Input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navio2ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navio2ros': ['/home/pi/catkin_ws/src/navio2ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navio2ros::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41bfe857689e03cf3cd507d1cb1bac8c";
  }

  static const char* value(const ::navio2ros::Input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41bfe857689e03cfULL;
  static const uint64_t static_value2 = 0x3cd507d1cb1bac8cULL;
};

template<class ContainerAllocator>
struct DataType< ::navio2ros::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navio2ros/Input";
  }

  static const char* value(const ::navio2ros::Input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navio2ros::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Barometer barometer\n\
ADC adc\n\
RC rc\n\
IMU imu\n\
GPS gps\n\
\n\
================================================================================\n\
MSG: navio2ros/Barometer\n\
float32 pressure\n\
float32 temperature\n\
float32 elevation\n\
\n\
================================================================================\n\
MSG: navio2ros/ADC\n\
float32[6] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/RC\n\
float32[12] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/IMU\n\
Accelerometer accelerometer\n\
Gyroscope gyroscope\n\
Magnetometer magnetometer\n\
\n\
================================================================================\n\
MSG: navio2ros/Accelerometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/Gyroscope\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/Magnetometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/GPS\n\
int32 status\n\
float32 mtow\n\
float32 longitude\n\
float32 latitude\n\
float32 elevation_ellipsoid\n\
float32 elevation_msl\n\
float32 horizontal_accuracy\n\
float32 vertical_accuracy\n\
";
  }

  static const char* value(const ::navio2ros::Input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navio2ros::Input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.barometer);
      stream.next(m.adc);
      stream.next(m.rc);
      stream.next(m.imu);
      stream.next(m.gps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navio2ros::Input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navio2ros::Input_<ContainerAllocator>& v)
  {
    s << indent << "barometer: ";
    s << std::endl;
    Printer< ::navio2ros::Barometer_<ContainerAllocator> >::stream(s, indent + "  ", v.barometer);
    s << indent << "adc: ";
    s << std::endl;
    Printer< ::navio2ros::ADC_<ContainerAllocator> >::stream(s, indent + "  ", v.adc);
    s << indent << "rc: ";
    s << std::endl;
    Printer< ::navio2ros::RC_<ContainerAllocator> >::stream(s, indent + "  ", v.rc);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::navio2ros::IMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "gps: ";
    s << std::endl;
    Printer< ::navio2ros::GPS_<ContainerAllocator> >::stream(s, indent + "  ", v.gps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIO2ROS_MESSAGE_INPUT_H
