// Generated by gencpp from file navio2ros/Output.msg
// DO NOT EDIT!


#ifndef NAVIO2ROS_MESSAGE_OUTPUT_H
#define NAVIO2ROS_MESSAGE_OUTPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navio2ros/PWM.h>
#include <navio2ros/LED.h>

namespace navio2ros
{
template <class ContainerAllocator>
struct Output_
{
  typedef Output_<ContainerAllocator> Type;

  Output_()
    : pwm()
    , led()  {
    }
  Output_(const ContainerAllocator& _alloc)
    : pwm(_alloc)
    , led(_alloc)  {
  (void)_alloc;
    }



   typedef  ::navio2ros::PWM_<ContainerAllocator>  _pwm_type;
  _pwm_type pwm;

   typedef  ::navio2ros::LED_<ContainerAllocator>  _led_type;
  _led_type led;




  typedef boost::shared_ptr< ::navio2ros::Output_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navio2ros::Output_<ContainerAllocator> const> ConstPtr;

}; // struct Output_

typedef ::navio2ros::Output_<std::allocator<void> > Output;

typedef boost::shared_ptr< ::navio2ros::Output > OutputPtr;
typedef boost::shared_ptr< ::navio2ros::Output const> OutputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navio2ros::Output_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navio2ros::Output_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navio2ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navio2ros': ['/home/pi/catkin_ws/src/navio2ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Output_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Output_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Output_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Output_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navio2ros::Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbd4021ec4ea8e258f9330f6d559599c";
  }

  static const char* value(const ::navio2ros::Output_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbd4021ec4ea8e25ULL;
  static const uint64_t static_value2 = 0x8f9330f6d559599cULL;
};

template<class ContainerAllocator>
struct DataType< ::navio2ros::Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navio2ros/Output";
  }

  static const char* value(const ::navio2ros::Output_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navio2ros::Output_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PWM pwm\n\
LED led\n\
\n\
================================================================================\n\
MSG: navio2ros/PWM\n\
float32[14] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/LED\n\
bool red\n\
bool green\n\
bool blue\n\
";
  }

  static const char* value(const ::navio2ros::Output_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navio2ros::Output_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm);
      stream.next(m.led);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Output_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navio2ros::Output_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navio2ros::Output_<ContainerAllocator>& v)
  {
    s << indent << "pwm: ";
    s << std::endl;
    Printer< ::navio2ros::PWM_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm);
    s << indent << "led: ";
    s << std::endl;
    Printer< ::navio2ros::LED_<ContainerAllocator> >::stream(s, indent + "  ", v.led);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIO2ROS_MESSAGE_OUTPUT_H
