// Generated by gencpp from file navio2ros/Vehicle.msg
// DO NOT EDIT!


#ifndef NAVIO2ROS_MESSAGE_VEHICLE_H
#define NAVIO2ROS_MESSAGE_VEHICLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <navio2ros/Barometer.h>
#include <navio2ros/ADC.h>
#include <navio2ros/RC.h>
#include <navio2ros/IMU.h>
#include <navio2ros/GPS.h>
#include <navio2ros/PWM.h>
#include <navio2ros/LED.h>
#include <navio2ros/AHRS.h>

namespace navio2ros
{
template <class ContainerAllocator>
struct Vehicle_
{
  typedef Vehicle_<ContainerAllocator> Type;

  Vehicle_()
    : barometer()
    , adc()
    , rc()
    , imu()
    , gps()
    , pwm()
    , led()
    , ahrs()  {
    }
  Vehicle_(const ContainerAllocator& _alloc)
    : barometer(_alloc)
    , adc(_alloc)
    , rc(_alloc)
    , imu(_alloc)
    , gps(_alloc)
    , pwm(_alloc)
    , led(_alloc)
    , ahrs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::navio2ros::Barometer_<ContainerAllocator>  _barometer_type;
  _barometer_type barometer;

   typedef  ::navio2ros::ADC_<ContainerAllocator>  _adc_type;
  _adc_type adc;

   typedef  ::navio2ros::RC_<ContainerAllocator>  _rc_type;
  _rc_type rc;

   typedef  ::navio2ros::IMU_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef  ::navio2ros::GPS_<ContainerAllocator>  _gps_type;
  _gps_type gps;

   typedef  ::navio2ros::PWM_<ContainerAllocator>  _pwm_type;
  _pwm_type pwm;

   typedef  ::navio2ros::LED_<ContainerAllocator>  _led_type;
  _led_type led;

   typedef  ::navio2ros::AHRS_<ContainerAllocator>  _ahrs_type;
  _ahrs_type ahrs;




  typedef boost::shared_ptr< ::navio2ros::Vehicle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navio2ros::Vehicle_<ContainerAllocator> const> ConstPtr;

}; // struct Vehicle_

typedef ::navio2ros::Vehicle_<std::allocator<void> > Vehicle;

typedef boost::shared_ptr< ::navio2ros::Vehicle > VehiclePtr;
typedef boost::shared_ptr< ::navio2ros::Vehicle const> VehicleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navio2ros::Vehicle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navio2ros::Vehicle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navio2ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'navio2ros': ['/home/pi/catkin_ws/src/navio2ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Vehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navio2ros::Vehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Vehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navio2ros::Vehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Vehicle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navio2ros::Vehicle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navio2ros::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2febfc1276c558c16a1a94747227f3aa";
  }

  static const char* value(const ::navio2ros::Vehicle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2febfc1276c558c1ULL;
  static const uint64_t static_value2 = 0x6a1a94747227f3aaULL;
};

template<class ContainerAllocator>
struct DataType< ::navio2ros::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navio2ros/Vehicle";
  }

  static const char* value(const ::navio2ros::Vehicle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navio2ros::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Barometer barometer\n\
ADC adc\n\
RC rc\n\
IMU imu\n\
GPS gps\n\
PWM pwm\n\
LED led\n\
AHRS ahrs\n\
\n\
================================================================================\n\
MSG: navio2ros/Barometer\n\
float32 pressure\n\
float32 temperature\n\
float32 elevation\n\
\n\
================================================================================\n\
MSG: navio2ros/ADC\n\
float32[6] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/RC\n\
float32[12] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/IMU\n\
Accelerometer accelerometer\n\
Gyroscope gyroscope\n\
Magnetometer magnetometer\n\
\n\
================================================================================\n\
MSG: navio2ros/Accelerometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/Gyroscope\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/Magnetometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: navio2ros/GPS\n\
int32 status\n\
float32 mtow\n\
float32 longitude\n\
float32 latitude\n\
float32 elevation_ellipsoid\n\
float32 elevation_msl\n\
float32 horizontal_accuracy\n\
float32 vertical_accuracy\n\
\n\
================================================================================\n\
MSG: navio2ros/PWM\n\
float32[14] channel\n\
\n\
================================================================================\n\
MSG: navio2ros/LED\n\
bool red\n\
bool green\n\
bool blue\n\
\n\
================================================================================\n\
MSG: navio2ros/AHRS\n\
Angular angular\n\
\n\
================================================================================\n\
MSG: navio2ros/Angular\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::navio2ros::Vehicle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navio2ros::Vehicle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.barometer);
      stream.next(m.adc);
      stream.next(m.rc);
      stream.next(m.imu);
      stream.next(m.gps);
      stream.next(m.pwm);
      stream.next(m.led);
      stream.next(m.ahrs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vehicle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navio2ros::Vehicle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navio2ros::Vehicle_<ContainerAllocator>& v)
  {
    s << indent << "barometer: ";
    s << std::endl;
    Printer< ::navio2ros::Barometer_<ContainerAllocator> >::stream(s, indent + "  ", v.barometer);
    s << indent << "adc: ";
    s << std::endl;
    Printer< ::navio2ros::ADC_<ContainerAllocator> >::stream(s, indent + "  ", v.adc);
    s << indent << "rc: ";
    s << std::endl;
    Printer< ::navio2ros::RC_<ContainerAllocator> >::stream(s, indent + "  ", v.rc);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::navio2ros::IMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "gps: ";
    s << std::endl;
    Printer< ::navio2ros::GPS_<ContainerAllocator> >::stream(s, indent + "  ", v.gps);
    s << indent << "pwm: ";
    s << std::endl;
    Printer< ::navio2ros::PWM_<ContainerAllocator> >::stream(s, indent + "  ", v.pwm);
    s << indent << "led: ";
    s << std::endl;
    Printer< ::navio2ros::LED_<ContainerAllocator> >::stream(s, indent + "  ", v.led);
    s << indent << "ahrs: ";
    s << std::endl;
    Printer< ::navio2ros::AHRS_<ContainerAllocator> >::stream(s, indent + "  ", v.ahrs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIO2ROS_MESSAGE_VEHICLE_H
