# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from navio2ros/GPS.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GPS(genpy.Message):
  _md5sum = "eaff3430fb0e45c8c7614e5a10be7a35"
  _type = "navio2ros/GPS"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 status
float32 mtow
float32 longitude
float32 latitude
float32 elevation_ellipsoid
float32 elevation_msl
float32 horizontal_accuracy
float32 vertical_accuracy
"""
  __slots__ = ['status','mtow','longitude','latitude','elevation_ellipsoid','elevation_msl','horizontal_accuracy','vertical_accuracy']
  _slot_types = ['int32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       status,mtow,longitude,latitude,elevation_ellipsoid,elevation_msl,horizontal_accuracy,vertical_accuracy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GPS, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.status is None:
        self.status = 0
      if self.mtow is None:
        self.mtow = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.elevation_ellipsoid is None:
        self.elevation_ellipsoid = 0.
      if self.elevation_msl is None:
        self.elevation_msl = 0.
      if self.horizontal_accuracy is None:
        self.horizontal_accuracy = 0.
      if self.vertical_accuracy is None:
        self.vertical_accuracy = 0.
    else:
      self.status = 0
      self.mtow = 0.
      self.longitude = 0.
      self.latitude = 0.
      self.elevation_ellipsoid = 0.
      self.elevation_msl = 0.
      self.horizontal_accuracy = 0.
      self.vertical_accuracy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i7f().pack(_x.status, _x.mtow, _x.longitude, _x.latitude, _x.elevation_ellipsoid, _x.elevation_msl, _x.horizontal_accuracy, _x.vertical_accuracy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.status, _x.mtow, _x.longitude, _x.latitude, _x.elevation_ellipsoid, _x.elevation_msl, _x.horizontal_accuracy, _x.vertical_accuracy,) = _get_struct_i7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i7f().pack(_x.status, _x.mtow, _x.longitude, _x.latitude, _x.elevation_ellipsoid, _x.elevation_msl, _x.horizontal_accuracy, _x.vertical_accuracy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.status, _x.mtow, _x.longitude, _x.latitude, _x.elevation_ellipsoid, _x.elevation_msl, _x.horizontal_accuracy, _x.vertical_accuracy,) = _get_struct_i7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i7f = None
def _get_struct_i7f():
    global _struct_i7f
    if _struct_i7f is None:
        _struct_i7f = struct.Struct("<i7f")
    return _struct_i7f
