// Generated by gencpp from file beginner_tutorials/Input.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_INPUT_H
#define BEGINNER_TUTORIALS_MESSAGE_INPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beginner_tutorials/Barometer.h>
#include <beginner_tutorials/ADC.h>
#include <beginner_tutorials/RC.h>
#include <beginner_tutorials/IMU.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Input_
{
  typedef Input_<ContainerAllocator> Type;

  Input_()
    : barometer()
    , adc()
    , rc()
    , imu()  {
    }
  Input_(const ContainerAllocator& _alloc)
    : barometer(_alloc)
    , adc(_alloc)
    , rc(_alloc)
    , imu(_alloc)  {
  (void)_alloc;
    }



   typedef  ::beginner_tutorials::Barometer_<ContainerAllocator>  _barometer_type;
  _barometer_type barometer;

   typedef  ::beginner_tutorials::ADC_<ContainerAllocator>  _adc_type;
  _adc_type adc;

   typedef  ::beginner_tutorials::RC_<ContainerAllocator>  _rc_type;
  _rc_type rc;

   typedef  ::beginner_tutorials::IMU_<ContainerAllocator>  _imu_type;
  _imu_type imu;




  typedef boost::shared_ptr< ::beginner_tutorials::Input_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Input_<ContainerAllocator> const> ConstPtr;

}; // struct Input_

typedef ::beginner_tutorials::Input_<std::allocator<void> > Input;

typedef boost::shared_ptr< ::beginner_tutorials::Input > InputPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Input const> InputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Input_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Input_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/pi/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Input_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Input_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Input_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Input_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22c232fb67d50d195b4f6a0c22950751";
  }

  static const char* value(const ::beginner_tutorials::Input_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22c232fb67d50d19ULL;
  static const uint64_t static_value2 = 0x5b4f6a0c22950751ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Input";
  }

  static const char* value(const ::beginner_tutorials::Input_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Input_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Barometer barometer\n\
ADC adc\n\
RC rc\n\
IMU imu\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Barometer\n\
float32 pressure\n\
float32 temperature\n\
float32 elevation\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/ADC\n\
float32[6] channel\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/RC\n\
float32[12] channel\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/IMU\n\
Accelerometer accelerometer\n\
Gyroscope gyroscope\n\
Magnetometer magnetometer\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Accelerometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Gyroscope\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Magnetometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::beginner_tutorials::Input_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Input_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.barometer);
      stream.next(m.adc);
      stream.next(m.rc);
      stream.next(m.imu);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Input_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Input_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Input_<ContainerAllocator>& v)
  {
    s << indent << "barometer: ";
    s << std::endl;
    Printer< ::beginner_tutorials::Barometer_<ContainerAllocator> >::stream(s, indent + "  ", v.barometer);
    s << indent << "adc: ";
    s << std::endl;
    Printer< ::beginner_tutorials::ADC_<ContainerAllocator> >::stream(s, indent + "  ", v.adc);
    s << indent << "rc: ";
    s << std::endl;
    Printer< ::beginner_tutorials::RC_<ContainerAllocator> >::stream(s, indent + "  ", v.rc);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::beginner_tutorials::IMU_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_INPUT_H
