// Generated by gencpp from file beginner_tutorials/PWM.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_PWM_H
#define BEGINNER_TUTORIALS_MESSAGE_PWM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct PWM_
{
  typedef PWM_<ContainerAllocator> Type;

  PWM_()
    : channel()  {
      channel.assign(0.0);
  }
  PWM_(const ContainerAllocator& _alloc)
    : channel()  {
  (void)_alloc;
      channel.assign(0.0);
  }



   typedef boost::array<float, 14>  _channel_type;
  _channel_type channel;




  typedef boost::shared_ptr< ::beginner_tutorials::PWM_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::PWM_<ContainerAllocator> const> ConstPtr;

}; // struct PWM_

typedef ::beginner_tutorials::PWM_<std::allocator<void> > PWM;

typedef boost::shared_ptr< ::beginner_tutorials::PWM > PWMPtr;
typedef boost::shared_ptr< ::beginner_tutorials::PWM const> PWMConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::PWM_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::PWM_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/pi/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::PWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::PWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::PWM_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::PWM_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::PWM_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::PWM_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::PWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b89efea741cb84dd797924caac76de6";
  }

  static const char* value(const ::beginner_tutorials::PWM_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b89efea741cb84dULL;
  static const uint64_t static_value2 = 0xd797924caac76de6ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::PWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/PWM";
  }

  static const char* value(const ::beginner_tutorials::PWM_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::PWM_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[14] channel\n\
";
  }

  static const char* value(const ::beginner_tutorials::PWM_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::PWM_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWM_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::PWM_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::PWM_<ContainerAllocator>& v)
  {
    s << indent << "channel[]" << std::endl;
    for (size_t i = 0; i < v.channel.size(); ++i)
    {
      s << indent << "  channel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.channel[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_PWM_H
