// Generated by gencpp from file beginner_tutorials/Vehicle.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_VEHICLE_H
#define BEGINNER_TUTORIALS_MESSAGE_VEHICLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <beginner_tutorials/Input.h>
#include <beginner_tutorials/Output.h>
#include <beginner_tutorials/AHRS.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Vehicle_
{
  typedef Vehicle_<ContainerAllocator> Type;

  Vehicle_()
    : input()
    , output()
    , ahrs()  {
    }
  Vehicle_(const ContainerAllocator& _alloc)
    : input(_alloc)
    , output(_alloc)
    , ahrs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::beginner_tutorials::Input_<ContainerAllocator>  _input_type;
  _input_type input;

   typedef  ::beginner_tutorials::Output_<ContainerAllocator>  _output_type;
  _output_type output;

   typedef  ::beginner_tutorials::AHRS_<ContainerAllocator>  _ahrs_type;
  _ahrs_type ahrs;




  typedef boost::shared_ptr< ::beginner_tutorials::Vehicle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Vehicle_<ContainerAllocator> const> ConstPtr;

}; // struct Vehicle_

typedef ::beginner_tutorials::Vehicle_<std::allocator<void> > Vehicle;

typedef boost::shared_ptr< ::beginner_tutorials::Vehicle > VehiclePtr;
typedef boost::shared_ptr< ::beginner_tutorials::Vehicle const> VehicleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Vehicle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Vehicle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'beginner_tutorials': ['/home/pi/catkin_ws/src/beginner_tutorials/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Vehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Vehicle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Vehicle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da90bcd421369e980b50dd533315976a";
  }

  static const char* value(const ::beginner_tutorials::Vehicle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda90bcd421369e98ULL;
  static const uint64_t static_value2 = 0x0b50dd533315976aULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Vehicle";
  }

  static const char* value(const ::beginner_tutorials::Vehicle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Input input\n\
Output output\n\
AHRS ahrs\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Input\n\
Barometer barometer\n\
ADC adc\n\
RC rc\n\
IMU imu\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Barometer\n\
float32 pressure\n\
float32 temperature\n\
float32 elevation\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/ADC\n\
float32[6] channel\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/RC\n\
float32[12] channel\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/IMU\n\
Accelerometer accelerometer\n\
Gyroscope gyroscope\n\
Magnetometer magnetometer\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Accelerometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Gyroscope\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Magnetometer\n\
float32 x\n\
float32 y\n\
float32 z\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Output\n\
PWM pwm\n\
LED led\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/PWM\n\
float32[14] channel\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/LED\n\
bool red\n\
bool green\n\
bool blue\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/AHRS\n\
Angular angular\n\
\n\
================================================================================\n\
MSG: beginner_tutorials/Angular\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::beginner_tutorials::Vehicle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
      stream.next(m.output);
      stream.next(m.ahrs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vehicle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Vehicle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Vehicle_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    s << std::endl;
    Printer< ::beginner_tutorials::Input_<ContainerAllocator> >::stream(s, indent + "  ", v.input);
    s << indent << "output: ";
    s << std::endl;
    Printer< ::beginner_tutorials::Output_<ContainerAllocator> >::stream(s, indent + "  ", v.output);
    s << indent << "ahrs: ";
    s << std::endl;
    Printer< ::beginner_tutorials::AHRS_<ContainerAllocator> >::stream(s, indent + "  ", v.ahrs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_VEHICLE_H
