# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from me457common/IMU.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import me457common.msg

class IMU(genpy.Message):
  _md5sum = "33ff63b96a03311723bbe1dce9705773"
  _type = "me457common/IMU"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """Accelerometer accelerometer
Gyroscope gyroscope
Magnetometer magnetometer

================================================================================
MSG: me457common/Accelerometer
float32 x
float32 y
float32 z

================================================================================
MSG: me457common/Gyroscope
float32 x
float32 y
float32 z

================================================================================
MSG: me457common/Magnetometer
float32 x
float32 y
float32 z
"""
  __slots__ = ['accelerometer','gyroscope','magnetometer']
  _slot_types = ['me457common/Accelerometer','me457common/Gyroscope','me457common/Magnetometer']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accelerometer,gyroscope,magnetometer

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(IMU, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accelerometer is None:
        self.accelerometer = me457common.msg.Accelerometer()
      if self.gyroscope is None:
        self.gyroscope = me457common.msg.Gyroscope()
      if self.magnetometer is None:
        self.magnetometer = me457common.msg.Magnetometer()
    else:
      self.accelerometer = me457common.msg.Accelerometer()
      self.gyroscope = me457common.msg.Gyroscope()
      self.magnetometer = me457common.msg.Magnetometer()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.accelerometer is None:
        self.accelerometer = me457common.msg.Accelerometer()
      if self.gyroscope is None:
        self.gyroscope = me457common.msg.Gyroscope()
      if self.magnetometer is None:
        self.magnetometer = me457common.msg.Magnetometer()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9f().pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.accelerometer is None:
        self.accelerometer = me457common.msg.Accelerometer()
      if self.gyroscope is None:
        self.gyroscope = me457common.msg.Gyroscope()
      if self.magnetometer is None:
        self.magnetometer = me457common.msg.Magnetometer()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z,) = _get_struct_9f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9f = None
def _get_struct_9f():
    global _struct_9f
    if _struct_9f is None:
        _struct_9f = struct.Struct("<9f")
    return _struct_9f
