// Generated by gencpp from file me457common/AHRS.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_AHRS_H
#define ME457COMMON_MESSAGE_AHRS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <me457common/Angular.h>

namespace me457common
{
template <class ContainerAllocator>
struct AHRS_
{
  typedef AHRS_<ContainerAllocator> Type;

  AHRS_()
    : angular()  {
    }
  AHRS_(const ContainerAllocator& _alloc)
    : angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::me457common::Angular_<ContainerAllocator>  _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::me457common::AHRS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::AHRS_<ContainerAllocator> const> ConstPtr;

}; // struct AHRS_

typedef ::me457common::AHRS_<std::allocator<void> > AHRS;

typedef boost::shared_ptr< ::me457common::AHRS > AHRSPtr;
typedef boost::shared_ptr< ::me457common::AHRS const> AHRSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::AHRS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::AHRS_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::AHRS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::AHRS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::AHRS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::AHRS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::AHRS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::AHRS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::AHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a8f2e835f7df7c60991a6cba8353dd78";
  }

  static const char* value(const ::me457common::AHRS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa8f2e835f7df7c60ULL;
  static const uint64_t static_value2 = 0x991a6cba8353dd78ULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::AHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/AHRS";
  }

  static const char* value(const ::me457common::AHRS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::AHRS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Angular angular\n\
\n\
================================================================================\n\
MSG: me457common/Angular\n\
float32 roll\n\
float32 pitch\n\
float32 yaw\n\
";
  }

  static const char* value(const ::me457common::AHRS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::AHRS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AHRS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::AHRS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::AHRS_<ContainerAllocator>& v)
  {
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::me457common::Angular_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_AHRS_H
