// Generated by gencpp from file me457common/DCMotor.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_DCMOTOR_H
#define ME457COMMON_MESSAGE_DCMOTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct DCMotor_
{
  typedef DCMotor_<ContainerAllocator> Type;

  DCMotor_()
    : speed()  {
      speed.assign(0);
  }
  DCMotor_(const ContainerAllocator& _alloc)
    : speed()  {
  (void)_alloc;
      speed.assign(0);
  }



   typedef boost::array<int16_t, 2>  _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::me457common::DCMotor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::DCMotor_<ContainerAllocator> const> ConstPtr;

}; // struct DCMotor_

typedef ::me457common::DCMotor_<std::allocator<void> > DCMotor;

typedef boost::shared_ptr< ::me457common::DCMotor > DCMotorPtr;
typedef boost::shared_ptr< ::me457common::DCMotor const> DCMotorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::DCMotor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::DCMotor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::DCMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::DCMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::DCMotor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::DCMotor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::DCMotor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::DCMotor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::DCMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55e53b59e8500e0d573f34660001b31c";
  }

  static const char* value(const ::me457common::DCMotor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55e53b59e8500e0dULL;
  static const uint64_t static_value2 = 0x573f34660001b31cULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::DCMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/DCMotor";
  }

  static const char* value(const ::me457common::DCMotor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::DCMotor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[2] speed\n\
";
  }

  static const char* value(const ::me457common::DCMotor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::DCMotor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DCMotor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::DCMotor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::DCMotor_<ContainerAllocator>& v)
  {
    s << indent << "speed[]" << std::endl;
    for (size_t i = 0; i < v.speed.size(); ++i)
    {
      s << indent << "  speed[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.speed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_DCMOTOR_H
