// Generated by gencpp from file me457common/Encoder.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_ENCODER_H
#define ME457COMMON_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : count()  {
      count.assign(0);
  }
  Encoder_(const ContainerAllocator& _alloc)
    : count()  {
  (void)_alloc;
      count.assign(0);
  }



   typedef boost::array<int32_t, 2>  _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::me457common::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::me457common::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::me457common::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::me457common::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba144d1786533a74b485986151fda73c";
  }

  static const char* value(const ::me457common::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba144d1786533a74ULL;
  static const uint64_t static_value2 = 0xb485986151fda73cULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/Encoder";
  }

  static const char* value(const ::me457common::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[2] count\n\
";
  }

  static const char* value(const ::me457common::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "count[]" << std::endl;
    for (size_t i = 0; i < v.count.size(); ++i)
    {
      s << indent << "  count[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.count[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_ENCODER_H
