// Generated by gencpp from file me457common/LED.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_LED_H
#define ME457COMMON_MESSAGE_LED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct LED_
{
  typedef LED_<ContainerAllocator> Type;

  LED_()
    : red(false)
    , green(false)
    , blue(false)  {
    }
  LED_(const ContainerAllocator& _alloc)
    : red(false)
    , green(false)
    , blue(false)  {
  (void)_alloc;
    }



   typedef uint8_t _red_type;
  _red_type red;

   typedef uint8_t _green_type;
  _green_type green;

   typedef uint8_t _blue_type;
  _blue_type blue;





  typedef boost::shared_ptr< ::me457common::LED_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::LED_<ContainerAllocator> const> ConstPtr;

}; // struct LED_

typedef ::me457common::LED_<std::allocator<void> > LED;

typedef boost::shared_ptr< ::me457common::LED > LEDPtr;
typedef boost::shared_ptr< ::me457common::LED const> LEDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::LED_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::LED_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::LED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::LED_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::LED_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::LED_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::LED_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::LED_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::LED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "13bca4c90aa92e68023254cf5e82c226";
  }

  static const char* value(const ::me457common::LED_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x13bca4c90aa92e68ULL;
  static const uint64_t static_value2 = 0x023254cf5e82c226ULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::LED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/LED";
  }

  static const char* value(const ::me457common::LED_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::LED_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool red\n\
bool green\n\
bool blue\n\
";
  }

  static const char* value(const ::me457common::LED_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::LED_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.red);
      stream.next(m.green);
      stream.next(m.blue);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LED_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::LED_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::LED_<ContainerAllocator>& v)
  {
    s << indent << "red: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blue);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_LED_H
