// Generated by gencpp from file me457common/StepperServerResponse.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_STEPPERSERVERRESPONSE_H
#define ME457COMMON_MESSAGE_STEPPERSERVERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct StepperServerResponse_
{
  typedef StepperServerResponse_<ContainerAllocator> Type;

  StepperServerResponse_()
    : ready(0)  {
    }
  StepperServerResponse_(const ContainerAllocator& _alloc)
    : ready(0)  {
  (void)_alloc;
    }



   typedef int64_t _ready_type;
  _ready_type ready;





  typedef boost::shared_ptr< ::me457common::StepperServerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::StepperServerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct StepperServerResponse_

typedef ::me457common::StepperServerResponse_<std::allocator<void> > StepperServerResponse;

typedef boost::shared_ptr< ::me457common::StepperServerResponse > StepperServerResponsePtr;
typedef boost::shared_ptr< ::me457common::StepperServerResponse const> StepperServerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::StepperServerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::StepperServerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::StepperServerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::StepperServerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::StepperServerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::StepperServerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::StepperServerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::StepperServerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::StepperServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d74ca1ffb31881ab824e1d61313924a0";
  }

  static const char* value(const ::me457common::StepperServerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd74ca1ffb31881abULL;
  static const uint64_t static_value2 = 0x824e1d61313924a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::StepperServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/StepperServerResponse";
  }

  static const char* value(const ::me457common::StepperServerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::StepperServerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 ready\n\
\n\
";
  }

  static const char* value(const ::me457common::StepperServerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::StepperServerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ready);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepperServerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::StepperServerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::StepperServerResponse_<ContainerAllocator>& v)
  {
    s << indent << "ready: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ready);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_STEPPERSERVERRESPONSE_H
