// Generated by gencpp from file me457common/Stepper.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_STEPPER_H
#define ME457COMMON_MESSAGE_STEPPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace me457common
{
template <class ContainerAllocator>
struct Stepper_
{
  typedef Stepper_<ContainerAllocator> Type;

  Stepper_()
    : header()
    , step(0.0)
    , direction(0.0)  {
    }
  Stepper_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , step(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _step_type;
  _step_type step;

   typedef float _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::me457common::Stepper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::Stepper_<ContainerAllocator> const> ConstPtr;

}; // struct Stepper_

typedef ::me457common::Stepper_<std::allocator<void> > Stepper;

typedef boost::shared_ptr< ::me457common::Stepper > StepperPtr;
typedef boost::shared_ptr< ::me457common::Stepper const> StepperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::Stepper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::Stepper_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Stepper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Stepper_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Stepper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Stepper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Stepper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Stepper_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7750ba0dca8aa3b87101f7accbeb245f";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7750ba0dca8aa3b8ULL;
  static const uint64_t static_value2 = 0x7101f7accbeb245fULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/Stepper";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 step\n\
float32 direction\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::Stepper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.step);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stepper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::Stepper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::Stepper_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "step: ";
    Printer<float>::stream(s, indent + "  ", v.step);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_STEPPER_H
