// Generated by gencpp from file me457common/StepperServerRequest.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_STEPPERSERVERREQUEST_H
#define ME457COMMON_MESSAGE_STEPPERSERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct StepperServerRequest_
{
  typedef StepperServerRequest_<ContainerAllocator> Type;

  StepperServerRequest_()
    : steps(0)
    , direction(0)  {
    }
  StepperServerRequest_(const ContainerAllocator& _alloc)
    : steps(0)
    , direction(0)  {
  (void)_alloc;
    }



   typedef int64_t _steps_type;
  _steps_type steps;

   typedef int64_t _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::me457common::StepperServerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::StepperServerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct StepperServerRequest_

typedef ::me457common::StepperServerRequest_<std::allocator<void> > StepperServerRequest;

typedef boost::shared_ptr< ::me457common::StepperServerRequest > StepperServerRequestPtr;
typedef boost::shared_ptr< ::me457common::StepperServerRequest const> StepperServerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::StepperServerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::StepperServerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::StepperServerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::StepperServerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::StepperServerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::StepperServerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::StepperServerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::StepperServerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::StepperServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf198fa6e21ae42dd46f77dfd8067a64";
  }

  static const char* value(const ::me457common::StepperServerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf198fa6e21ae42dULL;
  static const uint64_t static_value2 = 0xd46f77dfd8067a64ULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::StepperServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/StepperServerRequest";
  }

  static const char* value(const ::me457common::StepperServerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::StepperServerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 steps\n\
int64 direction\n\
";
  }

  static const char* value(const ::me457common::StepperServerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::StepperServerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.steps);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepperServerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::StepperServerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::StepperServerRequest_<ContainerAllocator>& v)
  {
    s << indent << "steps: ";
    Printer<int64_t>::stream(s, indent + "  ", v.steps);
    s << indent << "direction: ";
    Printer<int64_t>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_STEPPERSERVERREQUEST_H
