// Generated by gencpp from file me457common/StepperServer.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_STEPPERSERVER_H
#define ME457COMMON_MESSAGE_STEPPERSERVER_H

#include <ros/service_traits.h>


#include <me457common/StepperServerRequest.h>
#include <me457common/StepperServerResponse.h>


namespace me457common
{

struct StepperServer
{

typedef StepperServerRequest Request;
typedef StepperServerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepperServer
} // namespace me457common


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::me457common::StepperServer > {
  static const char* value()
  {
    return "e3b7f051b4258c90902e0e504971ecbd";
  }

  static const char* value(const ::me457common::StepperServer&) { return value(); }
};

template<>
struct DataType< ::me457common::StepperServer > {
  static const char* value()
  {
    return "me457common/StepperServer";
  }

  static const char* value(const ::me457common::StepperServer&) { return value(); }
};


// service_traits::MD5Sum< ::me457common::StepperServerRequest> should match 
// service_traits::MD5Sum< ::me457common::StepperServer > 
template<>
struct MD5Sum< ::me457common::StepperServerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::me457common::StepperServer >::value();
  }
  static const char* value(const ::me457common::StepperServerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::me457common::StepperServerRequest> should match 
// service_traits::DataType< ::me457common::StepperServer > 
template<>
struct DataType< ::me457common::StepperServerRequest>
{
  static const char* value()
  {
    return DataType< ::me457common::StepperServer >::value();
  }
  static const char* value(const ::me457common::StepperServerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::me457common::StepperServerResponse> should match 
// service_traits::MD5Sum< ::me457common::StepperServer > 
template<>
struct MD5Sum< ::me457common::StepperServerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::me457common::StepperServer >::value();
  }
  static const char* value(const ::me457common::StepperServerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::me457common::StepperServerResponse> should match 
// service_traits::DataType< ::me457common::StepperServer > 
template<>
struct DataType< ::me457common::StepperServerResponse>
{
  static const char* value()
  {
    return DataType< ::me457common::StepperServer >::value();
  }
  static const char* value(const ::me457common::StepperServerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ME457COMMON_MESSAGE_STEPPERSERVER_H
