// Generated by gencpp from file me457common/Stepper.msg
// DO NOT EDIT!


#ifndef ME457COMMON_MESSAGE_STEPPER_H
#define ME457COMMON_MESSAGE_STEPPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me457common
{
template <class ContainerAllocator>
struct Stepper_
{
  typedef Stepper_<ContainerAllocator> Type;

  Stepper_()
    : step(0.0)
    , direction(0.0)  {
    }
  Stepper_(const ContainerAllocator& _alloc)
    : step(0.0)
    , direction(0.0)  {
  (void)_alloc;
    }



   typedef float _step_type;
  _step_type step;

   typedef float _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::me457common::Stepper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me457common::Stepper_<ContainerAllocator> const> ConstPtr;

}; // struct Stepper_

typedef ::me457common::Stepper_<std::allocator<void> > Stepper;

typedef boost::shared_ptr< ::me457common::Stepper > StepperPtr;
typedef boost::shared_ptr< ::me457common::Stepper const> StepperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me457common::Stepper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me457common::Stepper_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me457common

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'me457common': ['/home/pi/catkin_ws/src/me457common/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Stepper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me457common::Stepper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Stepper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me457common::Stepper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Stepper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me457common::Stepper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c78a48ed2819371bf5d1770f913c26c3";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc78a48ed2819371bULL;
  static const uint64_t static_value2 = 0xf5d1770f913c26c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me457common/Stepper";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me457common::Stepper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 step\n\
float32 direction\n\
";
  }

  static const char* value(const ::me457common::Stepper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me457common::Stepper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.step);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Stepper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me457common::Stepper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me457common::Stepper_<ContainerAllocator>& v)
  {
    s << indent << "step: ";
    Printer<float>::stream(s, indent + "  ", v.step);
    s << indent << "direction: ";
    Printer<float>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME457COMMON_MESSAGE_STEPPER_H
